/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'senthilkumar' at '6/20/17 4:02 AM' with Gradle 2.13
 *
 * @author senthilkumar, @date 6/20/17 4:02 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
